* org-html-style
** Requirements
   + ~org-mode >= 9.0~

** Usage
   Import CSS file into org file:
   #+begin_src html
   ,#+HTML_DOCTYPE: html5
   ,#+OPTIONS: html5-fancy html-style:nil
   ,#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="path/to/org-html-style.css" />
   #+end_src

   Other related variables need to set:
   #+begin_src emacs-lisp
   ;; export code as plain text with CSS selectors
   (setq org-html-htmlize-output-type 'css)

   ;; don't include builtin scripts
   (setq org-html-head-include-scripts nil)
   #+end_src

** About code highlight
   Code highlight is controlled by =org-html-htmlize-output-type=. It has three available values:
   1. =inline-css= - highlight code depends on current Emacs theme. It has potential problem of readability.
   2. =nil= - export code as plain text. You have to highlight code with other external tools.
   3. =css= export code with CSS selectors. You can highlight code with plain CSS.

   How to choose?:
   + If you don't need code highlight or want to rely on external tools to highlight code, use =nil=.
   + If you want to highlight code by using the CSS provided by org-html-style, use =css=.

   #+begin_quote
   So far, org-html-style doesn't provide support for code highlight. If you need this feature, customize the stylesheets generated by =(org-html-htmlize-generate-css)= by your own.
   #+end_quote

   + =inline-css= shouldn't be used in any case.

** About customizing HTML header
   #+begin_src org
   # CSS
   ,#+HTML_HEAD: <style> body { background: red; } </style>

   # JavaScript
   ,#+HTML_HEAD: <script src="path/to/js"></script>

   # HTML Keywords header
   ,#+KEYWORDS: org-mode,HTML,CSS,style
   #+end_src

** Available CSS selectors
   + [[https://orgmode.org/manual/CSS-support.html][CSS support]]
   + List of selectors generated by =(org-html-htmlize-generate-css)=.

** More
   + [[https://github.com/fniessen/refcard-org-mode][Refcard of org-mode]]
   + [[https://orgmode.org/manual/HTML-Export.html][HTML Export of org-mode]]
     + [[https://orgmode.org/manual/JavaScript-support.html#JavaScript-support][JavaScript Support]]
